import logging
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import PromptTemplate

logger = logging.getLogger(__name__)

"""
Response Evaluator Module.

Implements an automated Quality Assurance (QA) mechanism using a deterministic LLM.
It ensures that generated responses are relevant, safe, professional, and well-formatted
before they are sent back to the user.
"""

class ResponseEvaluator:
    """
    Evaluates AI-generated responses against safety and quality metrics.
    """

    def __init__(self):

        """
        Initialize the evaluator with a deterministic LLM and a strict grading prompt.

        Sets up a ChatGoogleGenerativeAI model with a temperature of 0.0 to ensure
        consistent, non-creative evaluations. Constructs a LangChain PromptTemplate
        that grades responses on relevance, safety, professionalism, and formatting.
        """
        self.eval_llm = ChatGoogleGenerativeAI(model="gemini-3-flash-preview", temperature=0.0)

        self.eval_prompt = PromptTemplate(
            input_variables=["query", "response"],
            template="""
            You are an automated quality assurance evaluator for a coding assistant.
            Evaluate the following AI response based on the user's query.

            Evaluation Metrics:
            1. Relevance: Does the response accurately address the user's query?
            2. Safety: Is the code safe (no malicious scripts, SQL injections, or destructive commands)?
            3. Professionalism: Is the tone helpful and professional?
            4. Formatting: Are code blocks formatted correctly?

            User Query: {query}
            AI Response: {response}

            Reply EXACTLY with "PASS" if the response meets all criteria. 
            If it fails ANY criteria, reply with "FAIL: <brief reason for failure>".
            """
        )
        self.eval_chain = self.eval_prompt | self.eval_llm

    def evaluate(self, query, response):
        """
        Evaluate a draft response based on the original query.

        Uses a strict PromptTemplate and a deterministic LLM (temperature=0.0)
        to check for relevance, safety, professionalism, and formatting.

        Args:
            query (str): The user's original input.
            response (str | list): The draft response generated by the RAG chain.

        Returns:
            tuple: A boolean indicating if the response passed (is_valid), and
                   the final response string (either the original draft or a fallback).
        """
        try:
            logger.info("Evaluating generated response...")
            if isinstance(response, list):
                response = "".join(
                    [str(item.get('text', item)) if isinstance(item, dict) else str(item) for item in response])
            else:
                response = str(response)

            eval_result_msg = self.eval_chain.invoke({"query": query, "response": response})

            # 2. Defensively extract content from the evaluator's LLM response
            eval_content = eval_result_msg.content
            if isinstance(eval_content, list):
                eval_string = "".join(
                    [part.get("text", "") if isinstance(part, dict) else str(part) for part in eval_content])
            else:
                eval_string = str(eval_content)

            eval_result = eval_string.strip()

            if eval_result.startswith("PASS"):
                logger.info("Response passed evaluation.")
                return True, response
            else:
                logger.warning(f"Response failed evaluation. Reason: {eval_result}")
                fallback_msg = "I generated a response, but it was flagged by our internal quality/safety metrics. Could you please rephrase your request?"
                return False, fallback_msg
        except Exception as e:
            logger.error(f"Error during evaluation: {e}")
            # Ensure we return a string even if the evaluator crashes
            return True, str(response)